Repository NotJustCode3/The_Complete_Recorder, pull requests merged in 2021-04, with the labels that each got.

#57 Bug fixes
  .idea/workspace.xml
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
Labels: bug

#62 Add Poster
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  Documentation/Project Poster.png
Labels: documentation

#65 Refactor/cleaning codebase
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  AppDevelopment/complete_recorder/ios/Podfile.lock
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/speech_text.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
Labels: refactoring

#67 Speech to Text Plugin
  .idea/The_Complete_Recorder.iml
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/android/build.gradle
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/speech_text.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
Labels: enhancement

#72 Shafiq wave UI
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
  AppDevelopment/complete_recorder/res/wave.png
Labels: enhancement

#74 Update Documentation
  .idea/The_Complete_Recorder.iml
  .idea/libraries/Dart_Packages.xml
  AppDevelopment/complete_recorder/ios/Podfile.lock
  AppDevelopment/complete_recorder/lib/App Pages/feature_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/speech_text.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
  AppDevelopment/complete_recorder/res/wave.png
  Documentation/Project Demo/Readme.md
  Documentation/Project Presentation.pdf
Labels: documentation

#75 Code Smells
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/speech_text.dart
Labels: refactoring

#76 Prototype
  Documentation/Capstone Final Documentation.pdf
  Documentation/Project Final Documentation.pdf
  Documentation/Prototype/Page1.png
  Documentation/Prototype/Page2.png
  Documentation/Prototype/Page3.png
  Documentation/Prototype/Page4.png
  Documentation/Prototype/Page5.png
  Documentation/Prototype/Page6.png
  Documentation/Prototype/Page7.png
  Documentation/Prototype/Readme.md
Labels: documentation
