Repository NotJustCode3/The_Complete_Recorder, pull requests merged in 2021-02, with the labels that each got.

#24 Github Folder Organization
  .DS_Store
  Documentation/.DS_Store
  Miscellaneous/.DS_Store
  Miscellaneous/Azeezat Script.pdf
  Miscellaneous/IMG_20190609_092923.jpg
  Miscellaneous/NotJustCode.png
  Miscellaneous/Slides_Screenshots/Readme.md
  Miscellaneous/Slides_Screenshots/SC_4.png
  Miscellaneous/Slides_Screenshots/scrum_report#2/Readme.md
  Miscellaneous/Slides_Screenshots/scrum_report#2/sr1.png
  Miscellaneous/Slides_Screenshots/sl_pg1.png
  Miscellaneous/Slides_Screenshots/sl_pg2.png
  Miscellaneous/Slides_Screenshots/sl_pg3.png
  Miscellaneous/Slides_Screenshots/sl_pg4.png
  Miscellaneous/Slides_Screenshots/sl_pg5.png
  Miscellaneous/Slides_Screenshots/sl_pg6.png
  Miscellaneous/Slides_Screenshots/sl_pg7.png
  Miscellaneous/Slides_Screenshots/sl_pg8.png
  Miscellaneous/Slides_Screenshots/sl_pg9.png
  Miscellaneous/Vlog 1.pdf
  Miscellaneous/Vlog 2 thumbnail.png
  Miscellaneous/Vlog1_thumbnail.png
  Miscellaneous/demo.png
  Miscellaneous/mfjae-2020_10_12_22_27.jpg
  Miscellaneous/parkse.png
  Miscellaneous/upload.txt
  Miscellaneous/vlog3_thumbnail.png
  Scrums/Readme.md
  Scrums/Scrum Report Out #1.pdf
  Scrums/Scrum Report Out #2.pdf
  Scrums/Scrum Report Out #3.pdf
  Scrums/Scrum Report Out #4.pdf
  Vlogs/Readme.md
  Vlogs/Vlog_#0/Readme.md
  Vlogs/Vlog_#1/Readme.md
  Vlogs/Vlog_#2/Readme.md
  Vlogs/Vlog_#3/Readme.md
Labels: documentation

#25 Code Refactoring
  AppDevelopment/complete_recorder/lib/App Pages/feature_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/test_recording.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  AppDevelopment/complete_recorder/lib/main.dart
Labels: documentation

#26 Update recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
Labels: enhancement

#27 Documentation
  Documentation/.DS_Store
  Documentation/Capstone Final Documentation.pdf
  Documentation/Project Abstract.pdf
  Documentation/Project Proposal.pdf
Labels: documentation

#29 Develop
  README.md
  Vlogs/Vlog_#4/Readme.md
Labels: documentation

#30 Update README.md
  README.md
Labels: bug

#32 Syncing
  Vlogs/.DS_Store
Labels: syncing

#33 Commit Function
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
Labels: syncing

#35 Commit scrum #5
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_brain.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
  Scrums/Scrum Report Out #5 - Bazaar.pdf
Labels: documentation

#36 Update README.md
  README.md
Labels: documentation
