Repository NotJustCode3/The_Complete_Recorder, pull requests merged in 2021-03, with the labels that each got.

#38 Add files via upload
  Scrums/Scrum Report Out #6.pdf
Labels: documentation

#39 Updating Readme.md
  README.md
Labels: documentation

#40 Layout, Theme and Design
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/ios/Podfile.lock
  AppDevelopment/complete_recorder/lib/App Pages/feature_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  AppDevelopment/complete_recorder/lib/main.dart
Labels: enhancement

#41 Layout, theme and design
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/ios/Podfile.lock
  AppDevelopment/complete_recorder/lib/App Pages/feature_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  AppDevelopment/complete_recorder/lib/main.dart
  Scrums/Scrum Report Out #6.pdf
Labels: enhancement

#42 Record bug fixes
  .idea/The_Complete_Recorder.iml
  .idea/libraries/Dart_SDK.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
Labels: enhancement

#44 Splash screen and Dismissible Widget
  .idea/The_Complete_Recorder.iml
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/fonts/LibreBarcode39Text-Regular.ttf
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/splash_screen.dart
  AppDevelopment/complete_recorder/lib/main.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
Labels: enhancement

#45 Updating Master Branch
  .idea/The_Complete_Recorder.iml
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/fonts/LibreBarcode39Text-Regular.ttf
  AppDevelopment/complete_recorder/lib/App Pages/recorded_list_view.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/splash_screen.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  AppDevelopment/complete_recorder/lib/main.dart
  AppDevelopment/complete_recorder/pubspec.lock
  AppDevelopment/complete_recorder/pubspec.yaml
Labels: bug, enhancement

#46 Updating the recording page record button with a container. I also ch…
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/lib/App Pages/feature_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
Labels: enhancement

#47 Adding Picture of DevOps Sprints
  .DS_Store
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/workspace.xml
  AppDevelopment/complete_recorder/lib/App Pages/feature_button.dart
  AppDevelopment/complete_recorder/lib/App Pages/folders.dart
  AppDevelopment/complete_recorder/lib/App Pages/record_list.dart
  AppDevelopment/complete_recorder/lib/App Pages/recording_page.dart
  AppDevelopment/complete_recorder/lib/App Pages/search_button.dart
  AppDevelopment/complete_recorder/lib/homepage.dart
  Documentation/.DS_Store
  Documentation/Sprints/.DS_Store
  Documentation/Sprints/Sprint 0.png
  Documentation/Sprints/Sprint 1.png
  Documentation/Sprints/Sprint 2.png
  Documentation/Sprints/Sprint 3.png
  Documentation/Sprints/Sprint 4.png
  Documentation/Sprints/Sprint 5.png
  Documentation/Sprints/Sprint 6.png
  Documentation/Sprints/Sprint 7.png
Labels: documentation
